//
//  Locations.swift
//  Berliners
//
//  Created by Martijn van Gogh on 08-03-16.
//  Copyright © 2016 Martijn van Gogh. All rights reserved.
//

import Foundation
import MapKit

struct Locations {
    static let pinTitle: [String] = [
        "Strandbar Charlies Beach",
        "Clärchens Ballhaus",
        "Yaam Beach",
        "Klunkerkranich",
        "TanzWirtschaft Kaffee Bar",
        "Rickenbacker's Music Inn",
        "Madame Claude Bar",
        "Gesundbrunnen Bunker",
        "Konnopke's Imbiss",
        "Curry 36",
        "Hallentrödelmarkt Treptow",
        "Golgatha Biergarten",
        "schleusenkrug am Spree",
        "Badeschiff im Spree",
        "Mauerpark vlooienmarkt",
        "Mom's Vietnamese Kitchen",
        "Saigon and More",
        "Mustafa s Gemuese Kebab",
        "Sisaket Thai's restaurant",
        "White Trash",
        "Bassy Cowboyclub",
        "Klo Kneippe",
        "Tuan's Hütte - Thai's restaurant",
        "Lemongrass - Thai restaurant",
        "Dan Thai Food - Thai restaurant",
        "Berlinische Gallery",
        "DDR museum",
        "Palace of tears",
        "Admiral brucke",
        "Holzmarkt aan de Spree",
        "Cafe am Neuen See Biergarten",
        "Prater Biergarten",
        "Hopfenreich",
        "IPA Bar",
        "Twinpigs",
        "Hops & Barley",
        "Home world beer Bar",
        "Strassenbrau",
        "Monterey Bar",
        "Heidenpeters",
        "Brauerei Rollberg",
        "Berliner Berg",
        "Make a break - Escaperoom",
        "Absinth-Depot",
        "Fleischgerei",
        "Pauly Saal",
        "Schwarzer Hahn",
        "The antlered bunny",
        "Urban Spree/Club Astra",
        "Long March Canteen - Chinees rest.",
        "Lavanderia Vecchia",
        "The Grand",
        "Monsieur Vuong",
        "Club Frannz",
        "Club Duncker"]
    
    static let pinLocation: [String] = [
        "Friedrichstraße 48",
        "Auguststraße 24",
        "Stralauer Platz 35",
        "Karl-Marx-Straße 66",
        "Torstraße 60",
        "Bundesallee 194B",
        "Lübbener Strasse 19",
        "Brunnenstraße 105",
        "Schönhauser Allee 44 B",
        "Mehringdamm 36",
        "Eichenstraße 4",
        "im Viktoriapark",
        "Müller-Breslau-Str",
        "Eichenstraße 4",
        "Mauerpark",
        "Rosa-Luxemburgstrasse 3",
        "Geisbergstrasse 12",
        "Mehringdamm 32",
        "Mauerstr. 76",
        "Am Flutgraben 2",
        "Schönhauser Allee 176a",
        "Leibnizstasse 57",
        "Dircksenstr. 40",
        "Simon-Dach-Str. 2",
        "Reinickendorfer Str. 96",
        "Alte Jakobstrasse 124-128",
        "Karl-Liebknecht-Straße 1",
        "Reichstagufer 17",
        "Admiralstraße",
        "Holzmarktstraße 19-30",
        "Lichtensteinallee 2",
        "Kastanienallee 7-9",
        "Sorauer Str. 31",
        "Karl-Marx-Straße 195",
        "Boddinstraße 57a",
        "Wühlischstraße 22/23",
        "Neue Bahnhofstraße 23",
        "Neue Bahnhofstraße 30",
        "Danziger Str. 61",
        "Markthalle Neun,Eisenbahnstraße 42-43",
        "Am Sudhaus 3",
        "Kopfstraße 59",
        "Müggelstraße 8",
        "weinsmeisterstrasse 4",
        "Schönhauserallee 8",
        "Auguststrasse 11-13",
        "Seumestrasse 23",
        "Oderstrasse 7",
        "Revalerstrasse 99",
        "Wrangelstrasse 20",
        "Flughafenstrasse 46",
        "Hirtenstrasse 4",
        "Alte Schönhauserstrasse 46",
        "Schönhauser Allee 36",
        "Dunckerstraße 64"]
    
    static let pinDescription: [String] = [
        "Vlakbij Checkpoint Charlie is dit met 1.800 m² strand een waar paradijs vooral voor de inwendige mens. Op het strand staan tal van food trucks waarvan'Burger de ville' één van de beste hamburgers in town serveert. Het is een beetje een klein dorpje, zoals je ook op festivals ziet.",
        "Dansen zoals er vroeger werd gedanst! Dat is Clärchens Ballhaus. De tent sluit wanneer de laatste gast is vertrokken. Als hij open is, is het een abslolute must om de spiegelzaal met een bezoek te verblijden. En als na al het dansen het zweet je in de bilnaad staat, dan is de biergarten een uitkomst! Muziek: Live-bands, Rock 'n roll, heel gevarieerd voor elk wat wils (geen dance)",
        "Yaam is overdag een hele relaxte plek aan de Spree, compleet met nepstrand. Yaam betekent 'Young African Art Market' maar behalve kunst is er ook veel streetfood/drinks te krijgen, natuurlijk uit de Afrikaanse keuken. In de avond is er veel live muziek, en zijn er erg toffe feesten. Bijkomend voordeel; Yaam is ook nog eens erg goedkoop!",
        "Op dit dakterras boven op de parkeergarage zijn de Berliners al eens geweest. Toen waren er vuurspugers en daar houden de Berliners niet van... Geen flauwekulletjes! Wel een mooi uitzicht, leuk voor een coctailtje of koude rakker met een prachtig uitzicht. Om er te komen moet je de lift nemen in de mall.",
        "Een club/dancing die volgens de verhalen de oude Oost-Duitse sfeer heeft weten te behouden. De club heeft een uitgebreid programma aan live-muziek, varierend van rock tot indie tot klezmer, vaak met een Oost-Europees ravelrandje Het is in ieder geval geen dance-club met dancemuziek. Zoals zo alle plaatsen een erg goede score op Tripadvsor!",
        "Rickebacker's lijkt op een traditionele Ierse Pub, maar dan met iedere dag live-muziek volgens eigen zeggen, van hoog niveau:-). Dat valt te bezien, want wij zijn als Berliners met bands als 'The identicle spectacles' natuurlijk verwend. Wellicht leuk om te bekijken wat er speelt. Rickenbacker's staat qua livemuziekkroegen wel bovenaan in de Berlijn-lijstjes op internet.",
        "Madame Claude was een voormalig bordeelhoudster, maar tegenwoordig is haar hoerenkeet omgebouwd tot dansvloer. Het blijft een vreemde tent, want alles staat op z'n kop (hangt aan het plafond).. Is een beetje een 'coole' bar/dancing met vaak live-muziek, maar ook die is van de underground soort! Wellicht een soort 'Nieuwe Anita?'",
        "Gesundbrunnen Bunker is een tunnelcomplex gebouwd door de DDR om de bevolking te beschermen tegen een nucleaire oorlog. De bunker is verbonden met de metro en kon maar 4 % van de Berlijnse bevolking beschermen. In de tijd van de muur zijn de gangenstelsels ook veel gebruikt om van Oost naar West te ontsnappen.",
        "Na het opknappen van de Berlijnse metro, opende Konnopke's Imbiss zijn deuren op exact de plaats waar deze zaak 80 jaar geleden ook voor het eerst was gevestigd. Naast curryworsten zijn er ook bockworsten en burgers te verkrijgen. Samen met Curry 36 onbetwist de beste curryworstenplek van Berljn!",
        "Curry 36 is samen met Konnopke's het walhalla op het gebied van curryworsten. Curry 36 is een snackstal, maar wel een waar de mensen letterlijk voor in de rij staan. Behalve curryworst zijn er uiteraard ook andere snacks te krijgen zoals schnitzel. De zaak bestaat al sinds 1949 en wordt door locals beschouwd als de beste worstenzaak!",
        "Wil je echt eens iets bizars beleven in Berlijn? Ga dan eens naar de rommelmarkt “Hallentrödelmarkt” in het oostelijke deel van de stad. Deze overdekte vlooienmarkt is te vergelijken met de Zwarte Markt maar dan op een veel kleiner oppervlak. Met het kleine oppervlak wordt echter wel efficiënt omgesprongen: soeppannen hangen aan het plafond en kasten staan tot de nok toe opgestapeld.",
        "Gelegen in het Victoriapark in Kruezberg is Golgatha niet een doorsnee biergarten. Het is een plaats waar hipsters en gezinnen, locals en toeristen dwars door elkaar komen. In het weekend is er vaak live-muziek.",
        "Schleusenkrug begon als een kleine kiosk langs de rivier. Deze spot heeft een lager gelegen terras dat op een kleine tak van de Spree uitkijkt. Er zijn barbecues in de zomer en in de snackkraam serveert men klassiekers zoals Wiener schnitzel , biefstuk en quiches. Op de foto's zag dit eruit als een fijne relaxte plek!",
        "Het Badeschiff is een zwembad dat in een schip in de Spree is gebouwd. In het bad mogen geen versnaperingen worden meegenomen, maar eromheen liggen volop strandbarretjes waar dat wel gegeten en gedronken kan worden. Bij warm weer (en dat komt nogal eens voor in Berlijn) een prima optie om verkoeling te zoeken! Het Badeschiff is onderdeel van een heel complex van tentjes dat samen Arena heet.",
        "Iedere zondag is er in het Mauerpark een vlooienmarkt. Het is de beroemdste vlooienmarkt van Berlijn, en aan het eind van de dag kun je in het Mauerpark op zondag als kers op de taart ook nog de karaoke bijwonen in het amfitheater,",
        "Vietnamees restaurant dat 11e staat op tripadvisor van 6000 + restaurant in Berlijn. Gevestigd in Mitte en laat op de avond nog steeds druk. Volgens de recensies goede, krokant gebakken eend.",
        "Vietnamees restaurant, nr. 14 (van 6000 + restaurants) in Berlijn. Goekoop en goed eten in Schöneberg.",
        "Mustafa's is de beste kebabzaak van Berlijn. Recensie op Tripadvisor (nr 17 van 600 restaurants!): 'Super lekkere kebab, ik zou er alleen geen 1,5 uur voor in de rij staan. Ons hotel zat er super dichtbij waardoor wij het moment hebben afgewacht dat de rij een stuk korter was en hebben 3 kwartier over gedaan. Broodje was wel erg lekker!'",
        "Één van de best gewaardeerde Thaise restaurants van Berlijn. Een uitgebreid assortiment en een certificaat van uitmuntendheid op Tripadvisor.",
        "White trash is een kruising tussen livemuziek, eten en een club. Gelegen in Prenzlauerberg is White trash anders dan anders, hoewel het wel vaak erg druk schijnt te zijn en de bediening niet altijd even snel. Deze plaats is het in ieder geval waard om even te checken!",
        "Burlesque club met veel livemuziek, optredens, etc. Volgens de verhalen een beetje als de Nieuwe Anita in Amsterdam. De muziek is tot de jaren 70, en dus geen techno-shit en dergelijke, maar black R & B, country, garage Rock 'n Roll en nog veel meer. Zeker het bezoeken waard!",
        "Beetje een rare plek om uit te gaan, maar misschien daarom ook wel weer leuk. Muziek uit vroeger tijden, en erg populair (nr. 11 tripadvisor uitgaanslocaties). Meer op eten gericht met als hoofdthema...... WC's!",
        "Het Thais restaurant waar we ieder jaar wel een keertje eten. Heerljke eend, erg lekkere curry's. Staat ook in de top 15 van beste Thaise restaurants in Berlijn, maar niet bovenaan!",
        "Volgens de recensies een van de beste Thaise restaurants van Berlijn. Eerste op foursquare (8.9) en ook erg hoog scorend op Tripadvisor. het proberen zeker waard!",
        "OOk erg hoog scorend Thai's restaurant op foursquare (8.8), maar op Tripadvisor niet zo bekend nog. Wellicht het proberen waard mochten we in de buurt zijn?",
        "Best aangeschreven msueum voor moderne kunst in Berlijn. Vooral veel hedendaagse kunst.",
        "Klein maar fijn interactief museum over de DDR-tijd. Wel erg druk vaak, dus aan te raden, maar op een stil moment van de dag.",
        "Gratis museum over de DDR ten tijde van de muur. Hier kun je proeven hoe de grensovergang tussen Oost en West was en welke verhalen daar nog van resteren. Soms benauwend, soms ontroerend en soms indrukwekkend. Trek een uurtje uit om dit museum te bezoeken!",
        "Een brug waar volgens velen een typische berlijnse laid back sfeer hangt. Je kunt er gewoon op straat zittend, lekker van een biertje genieten. Om 10 uur wordt het publiek weggestuurd door de smeris.",
        "Lekkere strandbar aan de Spree. Hippie-achtig, Erdinger op de tap.",
        "Prachtig gelegen aan het water van de Berlijnse Tiergarten één van de grootste biergarten van de stad.",
        "Prater biergarten in de wijk Prenzlauerberg is de oudste biertuin van de stad. Lange tafels, grote schnitzels en forse porties kartoffelsalade. Hoe Duits wil je het hebben?",
        "Mooi biercafé met ontzettend veel bieren op de tap, en een gezellige sfeer in Kreuzberg met als huisider een ... egel.. (hipsters)",
        "Biercafe met dansvloer achterin, waar 's avonds vaak DJ's draaien.",
        "Erg mooie pub om te zien, een beetje een buurtpub.",
        "Kleine brouwerij in Friederichshain die 3 eigen bieren op de tap heeft.",
        "Speciaalbier café",
        "Strassenbrau in friederichshain is ook een speciaalbieren café.",
        "Monterey is een cool biercafé die liefde voor bier en rock 'n roll mixt. Veel 60's en 70's muziek en veel lokaal bier op tap.",
        "Gevestigd in een markthalle 9, een soort foodhal ik denk vergelijkbaar met de hallen in oud-west.",
        "Brouwerij op de rollberg met naar zeggen ook een heerlijk terras.",
        "Favoriete bierbar van Hidde Ophof.",
        "Dit is de escaproom die we dit keer in Berlijn gaan spelen! oP zondag 15 mei om 15:30 is het zover. Er zijn 3 rooms, maar wij spelen de 'Tear down this wall'-room.",
        "Onze eigen Amsterdamse slijter Ton Overmars van het hoofddorpplein heeft er voor gezorgd dat absinth niet langer verboden is. In deze zaak is de 'groene fee' in allerlei variaties verkrijgbaar.",
        "Tip uit de gids van Bas. De Oostenrijkse eigenaar doet er alles aan om boven het gemiddelde Bvan Berlijn uit te steken, en dat lukt!",
        "Dit restaurant is omgebouwd tot een prachtige zaal in jaren 20 stijl. Bij goed weer kun je in de tuin zitten (maar daar zullen wij geenn last van hebben dit keer:-)",
        "Jan, de kok van deze zaak voert die Heimatküche. En op wat voor manier. Schwarzer Hahn heeft waarschijnlijk de allerlekkerste schnitzels van heel Berlijn!",
        "Leuke zaak met kleine bar, cocktails, een ruim assortiment whisky, en snel  contact met je buren!, uit de gids van Bas.",
        "Op een stuk voormalig spoorwegterrein vind je cafés, kroegen, een vlooienmarkt, club Astra, een biergarten en exposities van de plaatselijke kunstenaars. Meer urban ga je het niet vinden!",
        "In dit restaurant is het net of je een opiumkit uit de jaren 30 binnentreedt.Net als de aankleding van de ruimte, zijn ook de gerechten abslouut geweldig!",
        "In dit traditionele Italiaanse restaurant eet je aan lange tafels de heerlijkste gerechten. Gevestigd in een oude wasserette, met legendarische antipasti vooraf!",
        "Uit Bas' gids is dit een bar, club en terras (bij mooi weer) op de binnenplaats. Met name de bar weerspiegelt de vroege swingperiode van Berlijn.",
        "Één van de eerste Vietnamese restaurants van Berlijn.",
        "Frannz biedt voor elk wat wils. Je kunt hier terecht om te eten, te drinken, te dansen en om op groot scherm naar Tatort te kijken. De muziek is heel divers, van pop tot house en van schlager tot rock.",
        "Duncker is een kleine alternatieve club waar echte instrumenten nog de boventoon voeren. De muziek gaat vooral in de richting van indie, wave, gothic en psychedelische rock. Er vinden zowel concerten als dansavonden plaats"]
    
    static let pinImageName: [String] = [ //afbeelding op de pin
        "charlies.jpg",
        "clarchens.jpg",
        "yaam.jpg",
        "Klunkerkranich.jpg",
        "kaffeeburger.jpg",
        "rickebackers.jpg",
        "claudes.jpg",
        "bunker.jpg",
        "konnopke.jpg",
        "curry36.jpg",
        "trodelmarkt.jpg",
        "golgatha.jpg",
        "sleusenkrug.jpg",
        "badeschiff.jpg",
        "flohmarkt.jpg",
        "moms.jpg",
        "saigon.jpg",
        "mustafa.jpg",
        "sisaket.jpg",
        "whitetrash.jpg",
        "bassy.jpg",
        "klo.jpg",
        "tuans.jpg",
        "lemongrass.jpg",
        "danthai.jpg",
        "gallery.jpg",
        "ddrmuseum.jpg",
        "palast.jpg",
        "admiralbrucke.jpg",
        "holzmarkt.jpg",
        "cafeamneuensee.jpg",
        "prater.jpg",
        "hopfenreich.jpg",
        "ipabar.jpg",
        "twinpigs.jpg",
        "hops.png",
        "homebeer.jpg",
        "strassenbrau.jpg",
        "montereybar.jpg",
        "heidenpeters.jpg",
        "rollberg.jpg",
        "berlinerberg.jpg",
        "escape.jpg",
        "absinth.jpg",
        "fleischerei.jpg",
        "pauly.jpg",
        "schwarzer.jpg",
        "bunny.jpg",
        "urban.jpg",
        "canteen.jpg",
        "vecchia.jpg",
        "thegrand.jpg",
        "monsieur.jpg",
        "frannz.png",
        "duncker.jpg"]
    static let discipline: [String] = [ //Kies uit Strand, Dansen, Berger .. Bepaalt de afbeelding van de pin.
        "Chillen",
        "Dansen",
        "Chillen",
        "Chillen",
        "Dansen",
        "Dansen",
        "Dansen",
        "Doen",
        "Eten",
        "Eten",
        "Doen",
        "Chillen",
        "Chillen",
        "Doen",
        "Doen",
        "Eten",
        "Eten",
        "Eten",
        "Eten",
        "Dansen",
        "Dansen",
        "Dansen",
        "Eten",
        "Eten",
        "Eten",
        "Doen",
        "Doen",
        "Doen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Chillen",
        "Doen",
        "Doen",
        "Eten",
        "Eten",
        "Eten",
        "Dansen",
        "Dansen",
        "Eten",
        "Eten",
        "Dansen",
        "Eten",
        "Dansen",
        "Dansen"]
    static let latitude: [CLLocationDegrees] = [
        52.508608,
        52.526822,
        52.508739,
        52.482305,
        52.528723,
        52.491973,
        52.499595,
        52.547878,
        52.540524,
        52.493510,
        52.497126,
        52.486718,
        52.51131,
        52.497888,
        52.541410,
        52.523527,
        52.497716,
        52.493875,
        52.509471,
        52.496768,
        52.531611,
        52.502251,
        52.523650,
        52.512546,
        52.547616,
        52.503944,
        52.519627,
        52.520885,
        52.495224,
        52.511103,
        52.510807,
        52.539777,
        52.499492,
        52.472946,
        52.480574,
        52.509008,
        52.507193,
        52.505613,
        52.539801,
        52.502079,
        52.479397,
        52.475876,
        52.512755,
        52.525374,
        52.529787,
        52.526441,
        52.510098,
        52.510334,
        52.507666,
        52.502913,
        52.481460,
        52.525497,
        52.526600,
        52.538398,
        52.546189]
    static let longitude: [CLLocationDegrees] = [
        13.390392,
        13.396811,
        13.433659,
        13.431578,
        13.408578,
        13.331443,
        13.437224,
        13.389277,
        13.412176,
        13.387723,
        13.452538,
        13.378582,
        13.336038,
        13.453734,
        13.402460,
        13.408965,
        13.340475,
        13.387874,
        13.387894,
        13.451712,
        13.411921,
        13.312965,
        13.406975,
        13.457176,
        13.368430,
        13.398121,
        13.387118,
        13.402744,
        13.415202,
        13.427234,
        13.344628,
        13.410127,
        13.439258,
        13.441225,
        13.431928,
        13.460602,
        13.470917,
        13.469409,
        13.422349,
        13.431337,
        13.431310,
        13.432806,
        13.470954,
        13.404963,
        13.410518,
        13.394359,
        13.459577,
        13.471281,
        13.451453,
        13.431005,
        13.426387,
        13.412532,
        13.407860,
        13.412730,
        13.423802]
    static let url: [String] = [
        "",
        "",
        "",
        "",
        "http://kaffeeburger.de/events/kategorie/konzert",
        "http://www.rickenbackers.de",
        "http://www.madameclaude.de",
        "https://www.tripadvisor.be/Attraction_Review-g187323-d3428324-Reviews-Gesundbrunnen_Bunker-Berlin.html",
        "http://konnopke-imbiss.de/Home.html",
        "http://www.curry36.de",
        "http://www.hallentrödelmarkt-berlin-treptow.de",
        "http://www.golgatha-berlin.de",
        "http://www.schleusenkrug.de",
        "http://www.arena.berlin/veranstaltungsort/badeschiff/",
        "vlooi",
        "",
        "",
        "",
        "",
        "",
        "http://www.whitetrash.com",
        "http://bassyclub.com",
        "",
        "Tuan's Hutte",
        "Lemongrass",
        "Danthai",
        "Berlinische gallery",
        "DDR museum",
        "Tranenpalast"]
}
